### PR TITLE
[65053] Rename wrapper to starter in form

### PR DESCRIPTION
**Pull request by akashchi**

### CODE REVIEW

**Review by yatarkan — CHANGES_REQUESTED** [review]
I suppose this PR should be divided into two separate PRs - one should be targeted to the `master` branch and include source changes, the second should be based on first and should be targeted to the `gh-pages` branch and include only changes with generated and built static files (that are in `/docs` directory)

**Comment by akashchi** [comment]
> I suppose this PR should be divided into two separate PRs - one should be targeted to the `master` branch and include source changes, the second should be based on first and should be targeted to the `gh-pages` branch and include only changes with generated and built static files (that are in `/docs` directory)

I did not understand about the second PR: you say that it should be based on the first one (which targetes the `master` and includes **only** source changes) and, at the same time, the second PR should include **only** changes in the `docs` directory. If the second PR is based on the first one, how come it includes only changes in the `docs` directory?

**Comment by yatarkan** [comment]
> > I suppose this PR should be divided into two separate PRs - one should be targeted to the `master` branch and include source changes, the second should be based on first and should be targeted to the `gh-pages` branch and include only changes with generated and built static files (that are in `/docs` directory)
> 
> I did not understand about the second PR: you say that it should be based on the first one (which targetes the `master` and includes **only** source changes) and, at the same time, the second PR should include **only** changes in the `docs` directory. If the second PR is based on the first one, how come it includes only changes in the `docs` directory?
> 
> Or you mean that changes in the `docs` should be built from the first PR?

Exactly, first we need to merge first PR to put source changes to `master` branch, then we need to checkout to `gh-pages` branch, merge `master` branch to `gh-pages` branch and after that run command to generate and build static that should appear in the `docs` folder - it would be the content for the second PR

**Comment by akashchi** [comment]
I have excluded the built static files - this PR contains only source changes.

**Review by yatarkan — APPROVED** [review]

**Pull request merged**
